Update heatzy-gui

diff --git a/heatzy/heatzy-gui b/heatzy/heatzy-gui
--- a/heatzy/heatzy-gui
+++ b/heatzy/heatzy-gui
@@ -42,28 +42,29 @@ HEATZY_TOKEN=$(grep "^token=" "${CONFIG_FILE}" | cut -d'=' -f2)
 if [ "${HEATZY_TOKEN}" = "" ]
 then
 	# ask for login and password
-	ANSWER=$(yad --center --width 500 --separator='#' --title "Heatzy pilote initialisation" --text "You first need to enter your Heatzy account login and password" --window-icon "/usr/share/icons/heatzy-pilote.png" --image "heatzy-pilote" --form --field="Login" "" --field="Password:H" "")
+	ANSWER=$(yad --center --width 500 --separator='#' --window-icon "/usr/share/icons/heatzy-pilote.png" --image "heatzy-pilote" \
+		--title "Heatzy pilote initialisation" --text "You first need to enter your Heatzy account login and password" \
+		--form --field="Login" "" --field="Password:H" "" )
 
-	# if selection validated
-	if [ "${ANSWER}" != "" ]
-	then
-		# extract login and password
-		HEATZY_LOGIN=$(echo "${ANSWER}" | cut -d'#' -f1)
-		HEATZY_PASSW=$(echo "${ANSWER}" | cut -d'#' -f2)
+	# if cancel, exit
+	[ "${ANSWER}" = "" ] && exit 1
 
-		# heatzy login attempt
-		[ "${HEATZY_LOGIN}" != "" -a "${HEATZY_PASSW}" != "" ] && heatzy --update --silent --login "${HEATZY_LOGIN}" --password "${HEATZY_PASSW}"
+	# extract login and password
+	HEATZY_LOGIN=$(echo "${ANSWER}" | cut -d'#' -f1)
+	HEATZY_PASSW=$(echo "${ANSWER}" | cut -d'#' -f2)
 
-		# re-read token from configuration
-		HEATZY_TOKEN=$(grep "^token=" "${CONFIG_FILE}" | cut -d'=' -f2)
-	fi
+	# heatzy login attempt
+	[ "${HEATZY_LOGIN}" != "" -a "${HEATZY_PASSW}" != "" ] && heatzy --update --silent --login "${HEATZY_LOGIN}" --password "${HEATZY_PASSW}"
+
+	# re-read token from configuration
+	HEATZY_TOKEN=$(grep "^token=" "${CONFIG_FILE}" | cut -d'=' -f2)
 fi
 
 # if token undefined,
 if [ "${HEATZY_TOKEN}" = "" ]
 then
 	# login failed
-	zenity --error --text="login failed to Heatzy server. Check login and password."
+	zenity --error --title="Heatzy pilote" --text="Login failed to Heatzy server\nCheck your login and password"
 
 	# exit
 	exit 1
@@ -74,7 +75,7 @@ else
 	TMP_FILE=$(mktemp --tmpdir "heatzy-XXXXXXXX")
 
 	# set default dialog box params
-	ARR_PARAM=( "--title" "Heatzy pilote control" "--text" "Select your Heatzy pilote state" )
+	ARR_PARAM=( "--title" "Heatzy pilote" "--text" "Select your Heatzy pilote state" )
 	ARR_PARAM=( "${ARR_PARAM[@]}" "--window-icon" "/usr/share/icons/heatzy-pilote.png" "--image" "heatzy-pilote" )
 	ARR_PARAM=( "${ARR_PARAM[@]}" "--form" ) 
 
