telegram-notify: Read config with support for comments and debug switch

diff --git a/telegram/telegram-notify b/telegram/telegram-notify
--- a/telegram/telegram-notify
+++ b/telegram/telegram-notify
@@ -25,6 +25,8 @@
 # ---------------------------------------------------
 
 # initialise variables
+DEBUG=""
+DEBUG_KEY=""
 TEXT=""
 ICON=""
 TYPE="text"
@@ -69,13 +71,61 @@ get_unicode_string() {
     # support unicode input even if current locale has no UTF-8
     local _lang=$LANG;
     local _lc_lang=${LANG,,}
-    if [ "${_lc_lang}" == "${_lc_lang/utf/}" ]; then # checking for lower case utf
+    if [ "${_lc_lang}" = "${_lc_lang/utf/}" ]; then # checking for lower case utf
       # currently no UTF-8 support, checking available locales for UTF-8 support
       _lang=$(get_utf_locale)
     fi
     command -v printf >/dev/null 2>&1 && LANG=$_lang printf "%b\n" "$1" && return 1;
     LANG=$_lang echo -e "$1" && return 0
     return 1
+}
+
+# -------------------------------------------------------
+#   Load config
+# -------------------------------------------------------
+
+trim() {
+  # remove leading whitespace characters
+  local _result=$1
+  _result="${_result#"${_result%%[![:space:]]*}"}"
+  # remove trailing whitespace characters
+  _result="${_result%"${_result##*[![:space:]]}"}"
+  printf "%s" "$_result"
+  return 0
+}
+
+read_config() {
+  # read config file removing comments
+  [ -f "${FILE_CONF}" ] || return 1
+  local _config=$(grep -oE "^[^#]*" "${FILE_CONF}") # read up to first '#' in line
+
+  echo "${_config}" | while read -er _line; do # split on new line
+    echo "$_line" | while IFS='=' read -a _KEY_VALUE; do # split on "="
+      local _key=$(trim "${_KEY_VALUE[0]}")
+      local _value=$(trim "${_KEY_VALUE[1]}")
+
+      # normalize key
+      _key=${_key//-/_}
+      _key=${_key^^} # upper case
+
+      [ "$_key" = "API_KEY" ]     && API_KEY=$_value
+      [ "$_key" = "USER_ID" ]     && USER_ID=$_value
+      [ "$_key" = "SOCKS_PROXY" ] && SOCKS_PROXY=$_value
+
+      if [ "${DEBUG}" = "ok" ]; then
+        if [ "$_key" = "API_KEY" ]; then # hide API key in debug output
+          [ "$_value" = "" ] && echo "[Warning] Config file: Key='${_key}'; Value=###missing###"
+          if [ ! "$_value" = "" ]; then
+            [ "$DEBUG_KEY" != "ok" ] && echo "[Info]    Config file: Key='${_key}'; Value=***** (show with --debug_key)"
+            [ "$DEBUG_KEY" =  "ok" ] && echo "[Info]    Config file: Key='${_key}'; Value='${_value}'"
+          fi
+        else
+          echo "[Info]    Config file: Key='${_key}'; Value='${_value}'"
+        fi
+      fi
+    done
+  done
+  return 0
 }
 
 # -------------------------------------------------------
@@ -111,7 +161,8 @@ then
   echo "  --question          Add a question mark icon"
   echo "  --icon <code>       Add an icon by UTF code (ex 1F355)"
   echo "Other options are :"
-  echo "  --debug             Display JSON answer for debug"
+  echo "  --debug             Display config file and JSON answer for debug"
+  echo "  --debug_key         Display config file data with API key for debug"
   echo "Here is an example of piped text :"
   echo "  echo 'text to be displayed' | telegram-notify --success --text -"
   exit
@@ -134,14 +185,15 @@ do
     "--silent") SILENT="true"; shift; ;;
     "--quiet") QUIET="true"; shift; ;;
     "--config") shift; FILE_CONF="$1"; shift; ;;
-    "--user") shift; USER_ID="$1"; shift; ;;
-    "--key") shift; API_KEY="$1"; shift; ;;
+    "--user") shift; ARG_USER_ID="$1"; shift; ;;
+    "--key") shift; ARG_API_KEY="$1"; shift; ;;
     "--success") ICON=$(get_unicode_string "\U2705"); shift; ;;
     "--warning") ICON=$(get_unicode_string "\U26A0"); shift; ;;
     "--error") ICON=$(get_unicode_string "\U1F6A8"); shift; ;;
     "--question") ICON=$(get_unicode_string "\U2753"); shift; ;;
     "--icon") shift; ICON=$(get_unicode_string "\U$1"); shift; ;;
     "--debug") DEBUG="ok"; shift; ;;
+    "--debug_key") DEBUG="ok"; DEBUG_KEY="ok"; shift; ;;
     *) shift; ;;
   esac
 done
@@ -156,23 +208,22 @@ then
 	# display used config file unless --quiet parameter is used
 	[ "${QUIET}" = "false" ] && echo "[Info] Using configuration file ${FILE_CONF}"
 
-	# if needed, load from configuration file
-	[ "${API_KEY}" = "" ] && API_KEY=$(grep "api-key=" "${FILE_CONF}" | cut -d'=' -f2)
-	[ "${USER_ID}" = "" ] && USER_ID=$(grep "user-id=" "${FILE_CONF}" | cut -d'=' -f2)
-
-	# load socks proxy from configuration file
-	SOCKS_PROXY=$(grep "socks-proxy=" "${FILE_CONF}" | cut -d'=' -f2)
+  read_config # use defaults from config
 else
 	# display warning unless --quiet parameter is used
 	[ "${QUIET}" = "false" ] && echo "[Warning] Configuration file missing ${FILE_CONF}"
 fi
+
+# overwrite defaults from config file with more specific command line arguments if provided
+[ "${ARG_USER_ID}" != "" ] && USER_ID=${ARG_USER_ID}
+[ "${ARG_API_KEY}" != "" ] && API_KEY=${ARG_API_KEY}
 
 # check API key and User ID
 [ "${API_KEY}" = "" ] && { echo "[Error] Please provide API key or set it in ${FILE_CONF}"; exit 1; }
 [ "${USER_ID}" = "" ] && { echo "[Error] Please provide User ID or set it in ${FILE_CONF}"; exit 1; }
 
 # Check for file existence
-[ "${FILE}" != "" ] && [ ! -f "${FILE}" ] && { echo "[error] File ${FILE} doesn't exist"; exit 1; }
+[ "${FILE}" != "" ] && [ ! -f "${FILE}" ] && { echo "[Error] File ${FILE} doesn't exist"; exit 1; }
 
 # generate temporary directory
 TMP_DIR=$(mktemp -t -d "telegram-XXXXXXXX")
